export const AUTH = 'zhiyun-auth';
export const SERVER = '/zhiyun-file';

export const imageType = ['jpg', 'png', 'jpeg', 'gif', 'mp4'];

export const officeFileType = ['ppt', 'pptx', 'doc', 'docx', 'xls', 'xlsx', 'pdf'];

/**
 * 可以用代码编辑器打开的文件后缀和 解析语言、 codemirror 解析模式 mode 映射关系
 * language：解析语言,
 * mime: codemirror 解析模式
 */
export const fileSuffixCodeModeMap = new Map([
  ['c', { language: 'C', mime: 'text/x-csrc' }],
  ['c++', { language: 'C++', mime: 'text/x-c++src' }],
  ['c#', { language: 'C#', mime: 'text/x-csharp' }],
  ['m', { language: 'Objective-C', mime: 'text/x-objectivec' }],
  ['go', { language: 'GO', mime: 'text/x-go' }],
  ['kt', { language: 'Kotlin', mime: 'text/x-java' }],
  ['css', { language: 'CSS', mime: 'text/css' }],
  ['less', { language: 'Less', mime: 'text/x-less' }],
  ['php', { language: 'PHP', mime: 'text/x-php' }],
  ['bat', { language: 'PowerShell', mime: 'application/x-powershell' }],
  ['py', { language: 'Python', mime: 'text/x-python' }],
  ['properties', { language: 'Properties', mime: 'text/x-properties' }],
  ['R', { language: 'R', mime: 'text/x-rsrc' }],
  ['rs', { language: 'Rust', mime: 'text/x-rustsrc' }],
  ['scss', { language: 'Scss', mime: 'text/x-scss' }],
  ['sass', { language: 'Sass', mime: 'text/x-sass' }],
  ['sh', { language: 'Shell', mime: 'text/x-sh' }],
  ['styl', { language: 'stylus', mime: 'text/x-styl' }],
  ['xml', { language: 'XML', mime: 'text/xml' }],
  ['html', { language: 'HTML', mime: 'text/html' }],
  ['http', { language: 'HTTP', mime: 'text/http' }],
  ['conf', { language: 'Nginx', mime: 'text/x-nginx-conf' }],
  ['java', { language: 'Java', mime: 'text/x-java' }],
  ['js', { language: 'JavaScript', mime: 'text/javascript' }],
  ['ts', { language: 'Typescript', mime: 'text/typescript' }],
  ['json', { language: 'JSON', mime: 'application/json' }],
  ['jsp', { language: 'JSP', mime: 'application/x-jsp' }],
  ['txt', { language: 'Txt', mime: '' }],
  ['vue', { language: 'Vue', mime: 'text/vue' }],
  ['sql', { language: 'SQL', mime: 'text/x-sql' }],
  ['swift', { language: 'Swift', mime: 'text/x-swift' }],
  ['yml', { language: 'YAML', mime: 'text/x-yaml' }],
]);

/**
 * codemirror 编辑器代码高亮主题列表
 */
export const codeMirrorThemeList = [
  '3024-day',
  '3024-night',
  'abbott',
  'abcdef',
  'ambiance-mobile',
  'ambiance',
  'ayu-dark',
  'ayu-mirage',
  'base16-dark',
  'base16-light',
  'bespin',
  'blackboard',
  'cobalt',
  'colorforth',
  'darcula',
  'dracula',
  'duotone-dark',
  'duotone-light',
  'eclipse',
  'elegant',
  'erlang-dark',
  'gruvbox-dark',
  'hopscotch',
  'icecoder',
  'idea',
  'isotope',
  'juejin',
  'lesser-dark',
  'liquibyte',
  'lucario',
  'material-darker',
  'material-ocean',
  'material-palenight',
  'material',
  'mbo',
  'mdn-like',
  'midnight',
  'monokai',
  'moxer',
  'neat',
  'neo',
  'night',
  'nord',
  'oceanic-next',
  'panda-syntax',
  'paraiso-dark',
  'paraiso-light',
  'pastel-on-dark',
  'railscasts',
  'rubyblue',
  'seti',
  'shadowfox',
  'solarized',
  'ssms',
  'the-matrix',
  'tomorrow-night',
  'tomorrow-night-bright',
  'tomorrow-night-eighties',
  'ttcn',
  'twilight',
  'vibrant-ink',
  'xq-dark',
  'xq-light',
  'yeti',
  'yonce',
  'zenburn',
];

export * from './MenuList';
